version: '3'
services:

  #Java Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: hello-java
    ports:
      - "8888:8888"
    container_name: app
    restart: unless-stopped
    tty: true
