metricbeat.config.modules:

  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

#processors:
#  - add_cloud_metadata: ~
  - add_docker_metadata: ~

metricbeat.autodiscover:
  providers:
    - type: docker
      labels.dedot: true
      templates:
        - condition:
            contains:
              docker.container.image: nginx
          config:
            - module: nginx
              metricsets: ["status"]
              hosts: "${data.host}:80"
  providers:
    - type: docker
      templates:
        - condition:
            contains:
              docker.container.image: nginx
          config:
            - type: container
              paths:
                - /var/lib/docker/containers/${data.docker.container.id}/*.log
              exclude_lines: ["^\\s+[\\-`('.|_]"]

output.elasticsearch:
  hosts: ["http://10.0.0.150:9200"]
  #username: '${ELASTICSEARCH_USERNAME:}'
  #password: '${ELASTICSEARCH_PASSWORD:}'
