- hosts: all
  become: yes
  tasks:
    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day
      tags: upgrade

    - name: "install Docker dependecies"
      apt:
        name:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
        - python3-pip
        - virtualenv
        - python3-setuptools

    - name: "add gpg docker key"
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
 
    - name: "add docker repo"
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable

    - name: "install docker"
      apt:
         name:
          - docker-ce
          - docker-ce-cli
          - containerd.io

    - name: docker permission
      command: chmod 666 /var/run/docker.sock

    - name: docker system enable
      command: sudo systemctl enable docker

    - name: Install docker-compose
      remote_user: ubuntu
      get_url: 
        url : https://github.com/docker/compose/releases/download/1.27.4/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: 'u+x,g+x'
     
    - name: install python docker module
      pip: 
         name: docker
